name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov flake8 black
        pip install -r my-eia-api-tool/requirements.txt
    - name: Lint with flake8
      run: |
        flake8 my-eia-api-tool/src --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 my-eia-api-tool/src --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Format with black
      run: black --check --diff my-eia-api-tool/src
    - name: Run tests
      run: pytest my-eia-api-tool/tests --cov=my-eia-api-tool/src --cov-report=xml